"""second

Revision ID: ce6cf23fd839
Revises: 
Create Date: 2026-02-12 16:58:31.824032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce6cf23fd839'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index('ix_projects_uuid', 'projects', ['uuid'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('asset_size', sa.Integer(), nullable=True),
    sa.Column('asset_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asset_type', 'assets', ['uuid'], unique=False)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index('ix_assets_project_id', 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_uuid'), 'assets', ['uuid'], unique=True)
    op.create_table('data_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('chunk_text', sa.String(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('chunk_created_at', sa.DateTime(), nullable=False),
    sa.Column('chunk_updated_at', sa.DateTime(), nullable=False),
    sa.Column('chunk_project_id', sa.Integer(), nullable=False),
    sa.Column('chunk_asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['chunk_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_chunks_id'), 'data_chunks', ['id'], unique=False)
    op.create_index('ix_data_chunks_project_id', 'data_chunks', ['id'], unique=False)
    op.create_index('ix_data_chunks_uuid', 'data_chunks', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_data_chunks_uuid', table_name='data_chunks')
    op.drop_index('ix_data_chunks_project_id', table_name='data_chunks')
    op.drop_index(op.f('ix_data_chunks_id'), table_name='data_chunks')
    op.drop_table('data_chunks')
    op.drop_index(op.f('ix_assets_uuid'), table_name='assets')
    op.drop_index('ix_assets_project_id', table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index('ix_asset_type', table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_projects_uuid', table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
